global:
  website: www.yourserver.fr
  scoreboard_title: §a§lDropper

games:
  easy_map_count: 2
  medium_map_count: 2
  hard_map_count: 1
  add_y_cord_on_spawns: true
  timer_before_drop: 5
  timer_sound: BLOCK_NOTE_BLOCK_PLING #NOTE_PLING
  portal_enter_sound: ENTITY_FIREWORK_ROCKET_BLAST
  timer_message: §aThe doors opens in §e%timer% §aseconds!
  go_message: §a§lDROP!
  timer_in_game: 600
  time_format: mm:SS
  reset_location: "§cReset location!"
  items:
    reset_location:
      slot: 4
      material: REDSTONE
      name: "§cReset location §r§7(Right-click)"
      description:
        - "§7Reset your location."
      extra:
        countdown_before_new_click: 2
        cant_reset_location: "§cPlease wait a bit before using it again!"
    player_visibility_on:
      slot: 8
      material: LIME_DYE
      name: "§7Player visibility: §aON"
      description:
        - "§7Hide or show the players around you."
    player_visibility_off:
      slot: 8
      material: GRAY_DYE
      name: "§7Player visibility: §cOFF"
      description:
        - "§7Hide or show the players around you."
  scoreboard:
    map_not_completed_symbol: §c✘
    map_completed_symbol: §a✔
    in_this_map_symbol: §6◀
    lines:
      - '§7%date% §8#%game_id%'
      - '{space}'
      - '§fTime Left: §a%time_left%'
      - '{space}'
      - '§fCurrent Map: §7(§e%current_map_count%§7/§b%total_map_count%§7)'
      - ' %map_completed_symbol% %map_name% %in_this_map_symbol%'
      - '{space}'
      - '§fTotal Time: §a%total_time%' # Only shows when the player finished.
      - '§fTotal Fails: §c%total_fails%'
      - '{space}'
      - '§e%website%'

wait_lobby:
  min_player: 2
  max_player: 10
  map_vote_count: 3
  time_format: mm:SS
  timer_start_seconds: 30
  join_message: §a%player% §ehas joined §a(§e%current_player%§a/§e%max_player%§a)!
  left_message: §a%player% §ehas left §a(§e%current_player%§a/§e%max_player%§a)!
  timer_message: §aThe game starts in §e%timer_seconds% §aseconds!
  timer_sound: BLOCK_NOTE_BLOCK_HAT #NOTE_HAT
  items:
    map_vote:
      slot: 0
      material: NAME_TAG
      name: "§e§lMap vote §r§7(Right-click)"
      description:
        - "§7Vote your favourite map!"
    leave:
      slot: 8
      material: RED_BED
      name: "§c§lLeave §r§7(Right-click)"
      description:
        - "§7Leave your current game."
  scoreboard:
    game_state:
      waiting: §fWaiting...
      starting: §fStarting in §a%timer%
    lines:
      - '§7%date% §8#%game_id%'
      - '{space}'
      - '§fPlayers: §a%current_player%§f/§a%max_player%'
      - '{space}'
      - '{game_state}'
      - '{space}'
      - '§fMap vote left: §a%player_map_vote_count%'
      - '{space}'
      - '§e%website%'

player:
  left_game: §cYou left the game.
  not_in_a_game: §cYou are not in a game!