global:
  website: www.yourserver.fr

games:
  easy_map_count: 2
  medium_map_count: 2
  hard_map_count: 1
  add_y_cord_on_spawns: true
  timer_before_drop: 5
  timer_sound: BLOCK_NOTE_BLOCK_PLING #NOTE_PLING
  timer_message: §aThe doors opens in §e%timer% §aseconds!
  go_message: §a§lDROP!

wait_lobby:
  min_player: 2
  max_player: 10
  map_vote_count: 3
  time_format: mm:SS
  timer_start_seconds: 30
  join_message: §a%player% §ehas joined §a(§e%current_player%§a/§e%max_player%§a)!
  left_message: §a%player% §ehas left §a(§e%current_player%§a/§e%max_player%§a)!
  timer_message: §aThe game starts in §e%timer_seconds% §aseconds!
  timer_sound: NOTE_STICKS #BLOCK_NOTE_BLOCK_HAT
  scoreboard:
    title: §a§lDropper
    game_state:
      waiting: §fWaiting...
      starting: §fStarting in §a%timer%
    slots:
      - "§7%date% §8#%game_id%"
      - "{space}"
      - "§fPlayers: §a%current_player%§f/§a%max_player%"
      - "{space}"
      - "{game_state}"
      - "{space}"
      - "§fMap vote left: §a%player_map_vote_count%"
      - "{space}"
      - "§e%website%"

player:
  left_game: §cYou left the game.
  not_in_a_game: §cYou are not in a game!