name: DropperReloaded
description: Dropper plugin
version: '1.0.0'
api-version: '1.13'
main: fr.loudo.dropperReloaded.DropperReloaded
authors: [ LOUDO ]
website: https://lucasll.xyz
softdepend: [ Citizens, ProtocolLib ]
commands:
  dropperadmin:
    description: DropperReloaded admin command.
    permission: dropper-reloaded.admin
    aliases: dropadm
  dropper:
    description: DropperReloaded player command.
    aliases: drop